version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.4.2
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - check-time

  db-fluentd:
    image: nanaones/fluentd:0.0.4
    volumes:
      - ./fluentd:/fluentd/etc
      - ../log:/logs
    links:
      - "elasticsearch"
    networks:
      - check-time

  DB-grafana:
    image: grafana/grafana:latest
    networks:
      - check-time
    ports: 
      - "13000:3000"

  DB-postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ../query/query.sql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      - POSTGRES_PASSWORD=8015
    ports: 
      - "5432:5432" 
    networks:
      - check-time

  python-main:
    image: nanaones/psycopg-test:0.0.4
    volumes:
      - ./logs:/logs
    environment:
      loop: 10
    networks:
      - check-time

networks:
  check-time: